### ISSUE TITLE
师傅请教一个问题博客当中"过去的考核靶场"

### ISSUE THREAD

**Issue by helloyw** [kaliworld/cut_file#1]
师傅请教一个问题博客当中"过去的考核靶场",提到hashcat可以使用Rule去破解速度缩短到一个小时以内破解任意非随机生成的密码），能否给个命令示例呢。

**Comment by kaliworld** [comment]
取决于个人经验，我之前在等保公司可以拿到所有单位的账号密码，可以观察出不同单位的密码规律，一般密码都符合类似这种规律：
https://github.com/berzerk0/Probable-Wordlists 你可以具体学习一下利用hashcat的rule破解

**Comment by helloyw** [comment]
> 取决于个人经验，我之前在等保公司可以拿到所有单位的账号密码，可以观察出不同单位的密码规律，一般密码都符合类似这种规律： https://github.com/berzerk0/Probable-Wordlists 你可以具体学习一下利用hashcat的rule破解

好的多谢师傅感谢回复
